config/routes.rb
Rails.application.routes.draw do


  devise_for :admins
resources :requests
resources :pianos
resources :contrabasses
resources :electric_guitars
resources :guitars
resources :pedals
resources :colors
resources :tipos
resources :captations
resources :materials
resources :cordas
resources :tarraxas
resources :bracos
resources :modelos

devise_for :users
root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/braco.rb
class Braco < ApplicationRecord
end

app/models/captation.rb
class Captation < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/contrabass.rb
class Contrabass < ApplicationRecord
  belongs_to :modelo
  belongs_to :braco
  belongs_to :tarraxa
  belongs_to :corda
  belongs_to :captation
end

app/models/corda.rb
class Corda < ApplicationRecord
end

app/models/guitar.rb
class Guitar < ApplicationRecord
  belongs_to :modelo
  belongs_to :braco
  belongs_to :tarraxa
  belongs_to :corda
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/modelo.rb
class Modelo < ApplicationRecord
end

app/models/pedal.rb
class Pedal < ApplicationRecord
end

app/models/piano.rb
class Piano < ApplicationRecord
  belongs_to :tipo
  belongs_to :color
  belongs_to :pedal
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :guitar
  belongs_to :electric_guitar
  belongs_to :contrabass
  belongs_to :piano
  belongs_to :user
end

app/models/tarraxa.rb
class Tarraxa < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/pedals_controller.rb
class PedalsController < ApplicationController
  before_action :set_pedal, only: [:show, :edit, :update, :destroy]

  # GET /pedals
  # GET /pedals.json
  def index
    @pedals = Pedal.all
  end

  # GET /pedals/1
  # GET /pedals/1.json
  def show
  end

  # GET /pedals/new
  def new
    @pedal = Pedal.new
  end

  # GET /pedals/1/edit
  def edit
  end

  # POST /pedals
  # POST /pedals.json
  def create
    @pedal = Pedal.new(pedal_params)

    respond_to do |format|
      if @pedal.save
        format.html { redirect_to @pedal, notice: 'Pedal was successfully created.' }
        format.json { render :show, status: :created, location: @pedal }
      else
        format.html { render :new }
        format.json { render json: @pedal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedals/1
  # PATCH/PUT /pedals/1.json
  def update
    respond_to do |format|
      if @pedal.update(pedal_params)
        format.html { redirect_to @pedal, notice: 'Pedal was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedal }
      else
        format.html { render :edit }
        format.json { render json: @pedal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedals/1
  # DELETE /pedals/1.json
  def destroy
    @pedal.destroy
    respond_to do |format|
      format.html { redirect_to pedals_url, notice: 'Pedal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedal
      @pedal = Pedal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedal_params
      params.require(:pedal).permit(:nome, :preco)
    end
end

app/helpers/bracos_helper.rb
module BracosHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/cordas_helper.rb
module CordasHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/pedals_helper.rb
module PedalsHelper
end

app/helpers/pianos_helper.rb
module PianosHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/pedals/_form.html.erb
<%= form_with(model: pedal, local: true) do |form| %>
  <% if pedal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedal.errors.count, "error") %> prohibited this pedal from being saved:</h2>

      <ul>
      <% pedal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :Preço %>
    <%= form.text_field :preco %>
  </div>

  <div class="actions">
    <%= form.submit :Cadastrar %>
  </div>
<% end %>

app/views/pedals/edit.html.erb
<h1>Editar Pedal</h1>

<%= render 'form', pedal: @pedal %>

<%= link_to 'Vizualizar', @pedal %> |
<%= link_to 'Voltar', pedals_path %>

app/views/pedals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedais de Piano</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedals.each do |pedal| %>
      <tr>
        <td><%= pedal.nome %></td>
        <td><%= pedal.preco %></td>
        <%if admin_signed_in?%>
          <td><%= link_to 'visualizar', pedal %></td>
          <td><%= link_to 'Editar', edit_pedal_path(pedal) %></td>
          <td><%= link_to 'Descadastrar', pedal, method: :delete, data: { confirm: 'tem certeza que deseja descadastrar?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if admin_signed_in?%>
<%= link_to 'Cadastrar Pedal', new_pedal_path %>
<%end%>

<%= link_to 'Voltar', root_path %>

app/views/pedals/new.html.erb
<h1>Cadastrar Pedal</h1>

<%= render 'form', pedal: @pedal %>

<%= link_to 'Voltar', pedals_path %>

app/views/pedals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pedal.nome %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @pedal.preco %>
</p>

<%= link_to 'Editar', edit_pedal_path(@pedal) %> |
<%= link_to 'Voltar', pedals_path %>