config/routes.rb
Rails.application.routes.draw do


  devise_for :admins
resources :requests
resources :pianos
resources :contrabasses
resources :electric_guitars
resources :guitars
resources :pedals
resources :colors
resources :tipos
resources :captations
resources :materials
resources :cordas
resources :tarraxas
resources :bracos
resources :modelos

devise_for :users
root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/braco.rb
class Braco < ApplicationRecord
end

app/models/captation.rb
class Captation < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/contrabass.rb
class Contrabass < ApplicationRecord
  belongs_to :modelo
  belongs_to :braco
  belongs_to :tarraxa
  belongs_to :corda
  belongs_to :captation
end

app/models/corda.rb
class Corda < ApplicationRecord
end

app/models/guitar.rb
class Guitar < ApplicationRecord
  belongs_to :modelo
  belongs_to :braco
  belongs_to :tarraxa
  belongs_to :corda
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/modelo.rb
class Modelo < ApplicationRecord
end

app/models/pedal.rb
class Pedal < ApplicationRecord
end

app/models/piano.rb
class Piano < ApplicationRecord
  belongs_to :tipo
  belongs_to :color
  belongs_to :pedal
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :guitar
  belongs_to :electric_guitar
  belongs_to :contrabass
  belongs_to :piano
  belongs_to :user
end

app/models/tarraxa.rb
class Tarraxa < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/bracos_helper.rb
module BracosHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/cordas_helper.rb
module CordasHelper
end

app/helpers/pedals_helper.rb
module PedalsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>LuthEasy</h1>
<h2>Seu Luthier Web!!!</h2>

<%if user_signed_in?%>
    <ul>
        <li><%= current_user.email%></li>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete%></li>
    </ul>
<%else %>
    <ul>
        <li> <%= link_to "Cadastre-se aqui", new_user_registration_path%></li>
        <li><%= link_to "Logar", new_user_session_path%></li>
    </ul>
<%end%>

<%if admin_signed_in?%>
    <ul>
        <li><%= current_admin.email%></li>
        <li><%= link_to "Lista de Intrumentos", requests_path%></li>
        <li><%= link_to "Sair", destroy_admin_session_path, method: :delete%></li>
    </ul>
<%else %>
    <ul>
        <p>Administrador?</p>
        <li> <%= link_to "Cadastre-se aqui como Admin", new_admin_registration_path%></li>
        <li><%= link_to "Logar", new_admin_session_path%></li>
    </ul>
<%end%>

<h3>Instrumentos disponiveis para fabricacao</h3>
<ul>
    <li> <%= link_to "Violao", guitars_path%></li>
    <li><%= link_to "Guitarra", electric_guitars_path%></li>
    <li><%= link_to "Contra-Baixo", contrabasses_path%></li>
    <li><%= link_to "Piano", pianos_path%></li>
</ul>

<h3>Catálogos</h3>
<ul>
    <li><%= link_to "Modelos", modelos_path %></li>
    <li><%= link_to "Tarraxas", tarraxas_path %></li>
    <li><%= link_to "Materiais - Guitarra", materials_path %></li>
    <li><%= link_to "Tipos - Piano", tipos_path %></li>
    <li><%= link_to "Cores - Piano", colors_path %></li>
    <li><%= link_to "Pedal - Piano", pedals_path %></li>
    <li><%= link_to "Braços- Instrumentos de Corda", bracos_path %></li>
     <li><%= link_to "Tipos de Captacao", captations_path %></li>
</ul>