config/routes.rb
Rails.application.routes.draw do


  devise_for :admins
resources :requests
resources :pianos
resources :contrabasses
resources :electric_guitars
resources :guitars
resources :pedals
resources :colors
resources :tipos
resources :captations
resources :materials
resources :cordas
resources :tarraxas
resources :bracos
resources :modelos

devise_for :users
root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/braco.rb
class Braco < ApplicationRecord
end

app/models/captation.rb
class Captation < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/contrabass.rb
class Contrabass < ApplicationRecord
  belongs_to :modelo
  belongs_to :braco
  belongs_to :tarraxa
  belongs_to :corda
  belongs_to :captation
end

app/models/corda.rb
class Corda < ApplicationRecord
end

app/models/guitar.rb
class Guitar < ApplicationRecord
  belongs_to :modelo
  belongs_to :braco
  belongs_to :tarraxa
  belongs_to :corda
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/modelo.rb
class Modelo < ApplicationRecord
end

app/models/pedal.rb
class Pedal < ApplicationRecord
end

app/models/piano.rb
class Piano < ApplicationRecord
  belongs_to :tipo
  belongs_to :color
  belongs_to :pedal
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :guitar
  belongs_to :electric_guitar
  belongs_to :contrabass
  belongs_to :piano
  belongs_to :user
end

app/models/tarraxa.rb
class Tarraxa < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bracos_controller.rb
class BracosController < ApplicationController
  before_action :set_braco, only: [:show, :edit, :update, :destroy]
  
  # GET /bracos
  # GET /bracos.json
  def index
    @bracos = Braco.all
  end

  # GET /bracos/1
  # GET /bracos/1.json
  def show
  end

  # GET /bracos/new
  def new
    @braco = Braco.new
  end

  # GET /bracos/1/edit
  def edit
  end

  # POST /bracos
  # POST /bracos.json
  def create
    @braco = Braco.new(braco_params)

    respond_to do |format|
      if @braco.save
        format.html { redirect_to @braco, notice: 'Braco was successfully created.' }
        format.json { render :show, status: :created, location: @braco }
      else
        format.html { render :new }
        format.json { render json: @braco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracos/1
  # PATCH/PUT /bracos/1.json
  def update
    respond_to do |format|
      if @braco.update(braco_params)
        format.html { redirect_to @braco, notice: 'Braco was successfully updated.' }
        format.json { render :show, status: :ok, location: @braco }
      else
        format.html { render :edit }
        format.json { render json: @braco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bracos/1
  # DELETE /bracos/1.json
  def destroy
    @braco.destroy
    respond_to do |format|
      format.html { redirect_to bracos_url, notice: 'Braco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_braco
      @braco = Braco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def braco_params
      params.require(:braco).permit(:qtde, :preco)
    end
end

app/helpers/bracos_helper.rb
module BracosHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/cordas_helper.rb
module CordasHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/pedals_helper.rb
module PedalsHelper
end

app/helpers/pianos_helper.rb
module PianosHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/bracos/_form.html.erb
<%= form_with(model: braco, local: true) do |form| %>
  <% if braco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(braco.errors.count, "error") %> prohibited this braco from being saved:</h2>

      <ul>
      <% braco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Quantidade_de_casas %>
    <%= form.number_field :qtde %>
  </div>

  <div class="field">
    <%= form.label :Preço %>
    <%= form.text_field :preco %>
  </div>

  <div class="actions">
    <%= form.submit :"Cadastrar Braço"%>
  </div>
<% end %>

app/views/bracos/edit.html.erb
<h1>Editing Braco</h1>

<%= render 'form', braco: @braco %>

<%= link_to 'Mostrar', @braco %> |
<%= link_to 'Voltar', bracos_path %>

app/views/bracos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Modelos de Braços </h1>

<table>
  <thead>
    <tr>
      <th>Quantidade de Casas</th>
      <th>Preço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bracos.each do |braco| %>
      <tr>
        <td><%= braco.qtde %></td>
        <td><%= braco.preco %></td>
        <%if admin_signed_in?%>
        <td><%= link_to 'Mostrar', braco %></td>
        <td><%= link_to 'Editar', edit_braco_path(braco) %></td>
        <td><%= link_to 'Descadastrar', braco, method: :delete, data: { confirm: 'Tem certeza que deseja descadastrar?' } %></td>
      <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if admin_signed_in?%>
<%= link_to 'Cadastrar Braço ', new_braco_path %>
<%end%>
<br>
<%= link_to 'Voltar', root_path %>

app/views/bracos/new.html.erb
<h1>New Braco</h1>

<%= render 'form', braco: @braco %>

<%= link_to 'Voltar', bracos_path %>

app/views/bracos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qtde:</strong>
  <%= @braco.qtde %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @braco.preco %>
</p>

<%= link_to 'Editar', edit_braco_path(@braco) %> |
<%= link_to 'Voltar', bracos_path %>